// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"tudo_IM1019/tudoIM_user/user_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/addFriend",
				Handler: AddFriendHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/user/friend_delete",
				Handler: FriendDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/friend_info",
				Handler: FriendInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/friend_list",
				Handler: FriendListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/friends_notice_update",
				Handler: FriendNoticeUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/search",
				Handler: SearchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/user_info",
				Handler: UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/user_info",
				Handler: UserInfoUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/varify",
				Handler: UserVerifyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/varifyList",
				Handler: FriendVerifyListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/verifyStatus",
				Handler: FriendVerifyStatusHandler(serverCtx),
			},
		},
	)
}
