// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"tudo_IM1019/tudoIM_chat/chat_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/api/chat/deleteHistory",
				Handler: chatDeleteHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/history",
				Handler: chatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/session",
				Handler: chatSessionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/chat/userTop",
				Handler: userTopHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/ws/chat",
				Handler: chatHandler(serverCtx),
			},
		},
	)
}
